<a href="https://colab.research.google.com/github/aminsiddik2810/data-science-2026/blob/https%2Fgithub.com%2Faminsiddik2810%2Fdata-science-2026.git/Pertemuan3_AminSiddikRangkuti_220401010124.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pertemuan 3 - Data Cleaning
## Nama  : Amin Siddik Rangkuti  
## Kelas : IF405  
## NIM   : 220401010124  
## Prodi : PJJ Informatika  

Notebook ini membahas pembersihan data housing_dirty.csv, meliputi:
- Deteksi missing values
- Penghapusan duplikat
- Normalisasi string
- Imputasi missing values
- Penanganan outlier dengan IQR Fence
- Validasi akhir
- Ekspor housing_clean.csv
- Ekstraksi data dari API JSONPlaceholder

In [119]:
import pandas as pd
import numpy as np
from scipy.stats.mstats import winsorize
import requests
from pandas import json_normalize

print("Semua library berhasil diimport.")

Semua library berhasil diimport.

In [120]:
import pandas as pd

# Membaca file hasil upload
dirty_file = "housing_dirty (1) (6).csv"
clean_file = "housing_clean (2) (4).csv"

# Load dataset
df_dirty = pd.read_csv(dirty_file)
df_clean = pd.read_csv(clean_file)

# Tampilkan informasi
print("DATASET DIRTY")
print("Shape:", df_dirty.shape)
display(df_dirty.head())

print("\nDATASET CLEAN")
print("Shape:", df_clean.shape)
display(df_clean.head())

DATASET DIRTY
Shape: (31, 7)

   id  luas_m2  harga_juta       kota  kamar  tahun_bangun kondisi
0   1     36.0       320.0    jakarta    2.0          2015    baik
1   2     45.0       450.0   Jakarta     2.0          2018    Baik
2   3     60.0       650.0    BANDUNG    3.0          2020   CUKUP
3   4     72.0         NaN    bandung    3.0          2019   cukup
4   5     90.0       980.0   surabaya    4.0          2021    baik

DATASET CLEAN
Shape: (30, 7)

   id  luas_m2  harga_juta      kota  kamar  tahun_bangun kondisi
0   1     36.0       320.0   Jakarta      2        2015.0    baik
1   2     45.0       450.0   Jakarta      2        2018.0    baik
2   3     60.0       650.0   Bandung      3        2020.0   cukup
3   4     72.0       815.0   Bandung      3        2019.0   cukup
4   5     90.0       980.0  Surabaya      4        2021.0    baik

In [121]:
file_list = list(uploaded.keys())

dirty_file = [f for f in file_list if "dirty" in f.lower()][0]
clean_file = [f for f in file_list if "clean" in f.lower()][0]

print("File dirty:", dirty_file)
print("File clean :", clean_file)

File dirty: housing_dirty (1) (6).csv
File clean : housing_clean (2) (4).csv

In [122]:
df_dirty = pd.read_csv(dirty_file)
df_clean_awal = pd.read_csv(clean_file)

print("DATASET DIRTY")
print("Shape:", df_dirty.shape)
display(df_dirty.head())

print("\nDATASET CLEAN AWAL")
print("Shape:", df_clean_awal.shape)
display(df_clean_awal.head())

DATASET DIRTY
Shape: (31, 7)

   id  luas_m2  harga_juta       kota  kamar  tahun_bangun kondisi
0   1     36.0       320.0    jakarta    2.0          2015    baik
1   2     45.0       450.0   Jakarta     2.0          2018    Baik
2   3     60.0       650.0    BANDUNG    3.0          2020   CUKUP
3   4     72.0         NaN    bandung    3.0          2019   cukup
4   5     90.0       980.0   surabaya    4.0          2021    baik

DATASET CLEAN AWAL
Shape: (30, 7)

   id  luas_m2  harga_juta      kota  kamar  tahun_bangun kondisi
0   1     36.0       320.0   Jakarta      2        2015.0    baik
1   2     45.0       450.0   Jakarta      2        2018.0    baik
2   3     60.0       650.0   Bandung      3        2020.0   cukup
3   4     72.0       815.0   Bandung      3        2019.0   cukup
4   5     90.0       980.0  Surabaya      4        2021.0    baik

In [123]:
df = df_dirty.copy()

print("Dataset yang akan dibersihkan berasal dari:", dirty_file)
print("Shape awal:", df.shape)

display(df.head())

Dataset yang akan dibersihkan berasal dari: housing_dirty (1) (6).csv
Shape awal: (31, 7)

   id  luas_m2  harga_juta       kota  kamar  tahun_bangun kondisi
0   1     36.0       320.0    jakarta    2.0          2015    baik
1   2     45.0       450.0   Jakarta     2.0          2018    Baik
2   3     60.0       650.0    BANDUNG    3.0          2020   CUKUP
3   4     72.0         NaN    bandung    3.0          2019   cukup
4   5     90.0       980.0   surabaya    4.0          2021    baik

In [124]:
print("INFO DATASET")
df.info()

print("\nSTATISTIK DESKRIPTIF")
display(df.describe(include="all"))

print("\nMISSING VALUES")
print(df.isnull().sum())

print("\nJUMLAH DUPLIKAT")
print(df.duplicated().sum())

INFO DATASET
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            31 non-null     int64
 1   luas_m2       29 non-null     float64
 2   harga_juta    28 non-null     float64
 3   kota          31 non-null     object
 4   kamar         30 non-null     float64
 5   tahun_bangun  31 non-null     int64
 6   kondisi       31 non-null     object
dtypes: float64(3), int64(2), object(2)
memory usage: 1.8+ KB

STATISTIK DESKRIPTIF

,id,luas_m2,harga_juta,kota,kamar,tahun_bangun,kondisi
count,31.000000,29.000000,28.000000,31,30.000000,31.000000,31
unique,NaN,NaN,NaN,16,NaN,NaN,7
top,NaN,NaN,NaN,jakarta,NaN,NaN,baik
freq,NaN,NaN,NaN,4,NaN,NaN,10
mean,15.322581,172.448276,7431.035714,NaN,4.366667,2011.645161,NaN
std,8.711629,355.755794,24120.959943,NaN,4.230296,22.650310,NaN
min,1.000000,30.000000,250.000000,NaN,1.000000,1935.000000,NaN
25%,8.500000,58.000000,597.500000,NaN,3.000000,2015.500000,NaN
50%,15.000000,78.000000,830.000000,NaN,3.000000,2019.000000,NaN
75%,22.500000,95.000000,1012.500000,NaN,4.000000,2021.000000,NaN
max,30.000000,1500.000000,99999.000000,NaN,20.000000,2024.000000,NaN

MISSING VALUES
id              0
luas_m2         2
harga_juta      3
kota            0
kamar           1
tahun_bangun    0
kondisi         0
dtype: int64

JUMLAH DUPLIKAT
1

In [125]:
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)

print("Persentase Missing Values:")
print(missing_pct[missing_pct > 0])

Persentase Missing Values:
luas_m2       6.45
harga_juta    9.68
kamar         3.23
dtype: float64

In [126]:
print("Shape sebelum hapus duplikat:", df.shape)
print("Jumlah duplikat sebelum:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("Shape setelah hapus duplikat:", df.shape)
print("Jumlah duplikat setelah:", df.duplicated().sum())

Shape sebelum hapus duplikat: (31, 7)
Jumlah duplikat sebelum: 1
Shape setelah hapus duplikat: (30, 7)
Jumlah duplikat setelah: 0

In [127]:
df["kota"] = df["kota"].astype(str).str.strip().str.title()
df["kondisi"] = df["kondisi"].astype(str).str.strip().str.lower()

print("Nilai unik kolom kota:")
print(df["kota"].unique())

print("\nNilai unik kolom kondisi:")
print(df["kondisi"].unique())

Nilai unik kolom kota:
['Jakarta' 'Bandung' 'Surabaya' 'Depok' 'Bogor']

Nilai unik kolom kondisi:
['baik' 'cukup' 'buruk' 'mewah']

In [128]:
df = df.replace(["", " ", "nan", "None", "NaN"], np.nan)

print("Missing values setelah normalisasi missing:")
print(df.isnull().sum())

Missing values setelah normalisasi missing:
id              0
luas_m2         2
harga_juta      3
kota            0
kamar           1
tahun_bangun    0
kondisi         0
dtype: int64

In [129]:
df["luas_m2"] = df["luas_m2"].fillna(df["luas_m2"].median())
df["harga_juta"] = df["harga_juta"].fillna(df["harga_juta"].median())
df["kamar"] = df["kamar"].fillna(df["kamar"].mode()[0])

if df["kota"].isnull().sum() > 0:
    df["kota"] = df["kota"].fillna(df["kota"].mode()[0])

if df["kondisi"].isnull().sum() > 0:
    df["kondisi"] = df["kondisi"].fillna(df["kondisi"].mode()[0])

print("Missing values setelah imputasi:")
print(df.isnull().sum())

Missing values setelah imputasi:
id              0
luas_m2         0
harga_juta      0
kota            0
kamar           0
tahun_bangun    0
kondisi         0
dtype: int64

In [130]:
def tangani_outlier_iqr(dataframe, kolom):
    Q1 = dataframe[kolom].quantile(0.25)
    Q3 = dataframe[kolom].quantile(0.75)
    IQR = Q3 - Q1

    batas_bawah = Q1 - 1.5 * IQR
    batas_atas = Q3 + 1.5 * IQR

    outlier = dataframe[
        (dataframe[kolom] < batas_bawah) |
        (dataframe[kolom] > batas_atas)
    ]

    print(f"Kolom: {kolom}")
    print(f"Q1: {Q1}")
    print(f"Q3: {Q3}")
    print(f"IQR: {IQR}")
    print(f"Batas bawah: {batas_bawah}")
    print(f"Batas atas: {batas_atas}")
    print(f"Jumlah outlier: {len(outlier)}")
    print("-" * 40)

    dataframe[kolom] = dataframe[kolom].clip(
        lower=batas_bawah,
        upper=batas_atas
    )

    return dataframe

In [131]:
kolom_outlier = ["harga_juta", "luas_m2", "tahun_bangun"]

for kolom in kolom_outlier:
    if kolom in df.columns:
        df = tangani_outlier_iqr(df, kolom)

print("Outlier selesai ditangani.")

Kolom: harga_juta
Q1: 612.5
Q3: 995.0
IQR: 382.5
Batas bawah: 38.75
Batas atas: 1568.75
Jumlah outlier: 4
----------------------------------------
Kolom: luas_m2
Q1: 58.5
Q3: 94.25
IQR: 35.75
Batas bawah: 4.875
Batas atas: 147.875
Jumlah outlier: 3
----------------------------------------
Kolom: tahun_bangun
Q1: 2015.25
Q3: 2021.0
IQR: 5.75
Batas bawah: 2006.625
Batas atas: 2029.625
Jumlah outlier: 3
----------------------------------------
Outlier selesai ditangani.

In [132]:
df["kamar"] = df["kamar"].round(0).astype(int)
df["tahun_bangun"] = df["tahun_bangun"].round(0).astype(int)

display(df.head())

   id  luas_m2  harga_juta      kota  kamar  tahun_bangun kondisi
0   1     36.0       320.0   Jakarta      2          2015    baik
1   2     45.0       450.0   Jakarta      2          2018    baik
2   3     60.0       650.0   Bandung      3          2020   cukup
3   4     72.0       810.0   Bandung      3          2019   cukup
4   5     90.0       980.0  Surabaya      4          2021    baik

In [133]:
print("Shape akhir:", df.shape)
print("Total missing values:", df.isnull().sum().sum())
print("Total duplikat:", df.duplicated().sum())

assert df.isnull().sum().sum() == 0, "Masih ada missing values!"
assert df.duplicated().sum() == 0, "Masih ada data duplikat!"

print("VALIDASI BERHASIL: dataset sudah bersih.")

Shape akhir: (30, 7)
Total missing values: 0
Total duplikat: 0
VALIDASI BERHASIL: dataset sudah bersih.

In [134]:
print("CLEAN BAWAAN")
print("Shape:", df_clean_awal.shape)
display(df_clean_awal.head())

print("\nCLEAN HASIL PROSES")
print("Shape:", df.shape)
display(df.head())

CLEAN BAWAAN
Shape: (30, 7)

   id  luas_m2  harga_juta      kota  kamar  tahun_bangun kondisi
0   1     36.0       320.0   Jakarta      2        2015.0    baik
1   2     45.0       450.0   Jakarta      2        2018.0    baik
2   3     60.0       650.0   Bandung      3        2020.0   cukup
3   4     72.0       815.0   Bandung      3        2019.0   cukup
4   5     90.0       980.0  Surabaya      4        2021.0    baik

CLEAN HASIL PROSES
Shape: (30, 7)

   id  luas_m2  harga_juta      kota  kamar  tahun_bangun kondisi
0   1     36.0       320.0   Jakarta      2          2015    baik
1   2     45.0       450.0   Jakarta      2          2018    baik
2   3     60.0       650.0   Bandung      3          2020   cukup
3   4     72.0       810.0   Bandung      3          2019   cukup
4   5     90.0       980.0  Surabaya      4          2021    baik

In [135]:
df.to_csv("housing_clean_final.csv", index=False)

print("File housing_clean_final.csv berhasil dibuat.")

File housing_clean_final.csv berhasil dibuat.

In [136]:
files.download("housing_clean_final.csv")

In [137]:
URL = "https://jsonplaceholder.typicode.com/users"

try:
    response = requests.get(URL, timeout=10)

    if response.status_code == 200:
        data_api = response.json()
        df_api = json_normalize(data_api, sep="_")

        print("Data API berhasil diambil.")
        display(df_api[["id", "name", "email", "address_city", "company_name"]])
    else:
        print("Gagal mengambil data. Status code:", response.status_code)

except requests.exceptions.RequestException as e:
    print("Terjadi error koneksi:", e)

Data API berhasil diambil.

,id,name,email,address_city,company_name
0,1,Leanne Graham,Sincere@april.biz,Gwenborough,Romaguera-Crona
1,2,Ervin Howell,Shanna@melissa.tv,Wisokyburgh,Deckow-Crist
2,3,Clementine Bauch,Nathan@yesenia.net,McKenziehaven,Romaguera-Jacobson
3,4,Patricia Lebsack,Julianne.OConner@kory.org,South Elvis,Robel-Corkery
4,5,Chelsey Dietrich,Lucio_Hettinger@annie.ca,Roscoeview,Keebler LLC
5,6,Mrs. Dennis Schulist,Karley_Dach@jasper.info,South Christy,Considine-Lockman
6,7,Kurtis Weissnat,Telly.Hoeger@billy.biz,Howemouth,Johns Group
7,8,Nicholas Runolfsdottir V,Sherwood@rosamond.me,Aliyaview,Abernathy Group
8,9,Glenna Reichert,Chaim_McDermott@dana.io,Bartholomebury,Yost and Sons
9,10,Clementina DuBuque,Rey.Padberg@karina.biz,Lebsackbury,Hoeger LLC

In [138]:
df_api.to_csv("jsonplaceholder_users.csv", index=False)

print("File jsonplaceholder_users.csv berhasil dibuat.")
files.download("jsonplaceholder_users.csv")

File jsonplaceholder_users.csv berhasil dibuat.

In [139]:
print("""
KESIMPULAN:

1. File housing_dirty dan housing_clean berhasil dimuat.
2. Dataset dirty digunakan sebagai data utama untuk proses cleaning.
3. Missing values berhasil ditangani dengan median dan modus.
4. Data duplikat berhasil dihapus.
5. Kolom kota dan kondisi berhasil dinormalisasi.
6. Outlier pada harga_juta, luas_m2, dan tahun_bangun berhasil ditangani dengan IQR Fence.
7. Validasi akhir menunjukkan tidak ada missing values dan tidak ada duplikat.
8. Dataset bersih berhasil diekspor menjadi housing_clean_final.csv.
9. Data dari API JSONPlaceholder berhasil diambil dan disimpan.
""")

KESIMPULAN:

1. File housing_dirty dan housing_clean berhasil dimuat.
2. Dataset dirty digunakan sebagai data utama untuk proses cleaning.
3. Missing values berhasil ditangani dengan median dan modus.
4. Data duplikat berhasil dihapus.
5. Kolom kota dan kondisi berhasil dinormalisasi.
6. Outlier pada harga_juta, luas_m2, dan tahun_bangun berhasil ditangani dengan IQR Fence.
7. Validasi akhir menunjukkan tidak ada missing values dan tidak ada duplikat.
8. Dataset bersih berhasil diekspor menjadi housing_clean_final.csv.
9. Data dari API JSONPlaceholder berhasil diambil dan disimpan.